// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_card: dynamic(() => import("./BlogCard")),
  rich_text: dynamic(() => import("./RichText")),
};
